### ISSUE TITLE
Unable to detect "cgum"

### ISSUE THREAD

**Issue by nimisha-agarwal** [GumTreeDiff/gumtree#119]
I have added "cgum" to the system path, however, I am still getting the same error. Can someone help me to resolve the error?
java.io.IOException: Cannot run program "cgum" (in directory "/tmp"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.gumtreediff.gen.c.CTreeGenerator.generate(CTreeGenerator.java:73)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromReader(TreeGenerator.java:37)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromFile(TreeGenerator.java:43)
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:43)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.getTreeContext(AbstractDiffClient.java:128)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.getSrcTreeContext(AbstractDiffClient.java:114)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.matchTrees(AbstractDiffClient.java:105)
	at com.github.gumtreediff.client.diff.TextDiff.run(TextDiff.java:98)
	at com.github.gumtreediff.client.Run.startClient(Run.java:80)
	at com.github.gumtreediff.client.Run.main(Run.java:108)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 10 more
** Error while running client diff: java.lang.NullPointerException

_Originally posted by @nimisha-agarwal in https://github.com/GumTreeDiff/gumtree/issues/23#issuecomment-450087167_

**Comment by jrfaller** [comment]
Mmm weird this normally works if cgum is in the path...

Can you try to put a link to gumtree in /usr/bin ?

**Comment by asejfia** [comment]
Hi, I am having the same issue suddenly after an update in my MAC. How did you solve this issue?

**Comment by asejfia** [comment]
Just in case someone has the same issue as me: I was using gumtree and cgum in an IntellijIDEA project and launching Idea from the terminal worked! For more information: https://youtrack.jetbrains.com/issue/IDEA-99154
