### ISSUE TITLE
The example "Computing the actions between two trees" does not work out-of-box

### ISSUE THREAD

**Issue by jose** [GumTreeDiff/gumtree#121]
Hi,

As the title says, the provided API example "Computing the actions between two trees" described in the [wiki](https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API) page throws an unexpected exception with GumTree v2.1.0 (the latest version available on the [Maven repository](https://mvnrepository.com/artifact/com.github.gumtreediff)).
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.reflections.Reflections.<init>(Reflections.java:141)
	at com.github.gumtreediff.client.Run.initGenerators(Run.java:56)
	at com.github.gumtreediff.client.Run.<clinit>(Run.java:80)
```

PS: I've setup a small [project](https://github.com/jose/gumtree_api_example) which triggers the above exception.

--
Best,
Jose

**Comment by jose** [comment]
Well, the example seems to be working just fine with the latest development (i.e., v2.1.2-SNAPSHOT).

**Comment by jose** [comment]
Duplicate #81.
