### ISSUE TITLE
Running gumtree on Windows for C++

### ISSUE THREAD

**Issue by ChunghaSung** [GumTreeDiff/gumtree#143]
Hi, I installed gumtree on my windows machine.
And, I installed srcML by setting the path.

But, when I tested my code with two java files for diffing, it works correctly, but when I tried to run on C++ files, it complains about running the process (srcml) under the specified path. So, I moved srcML.exe file under the directory, but it still complains.

Is there any way to solve this problem? 

Below is the error msg.
```
Exception in thread "main" java.io.IOException: Cannot run program "srcml" (in directory "C:\Users\USERNAME\AppData\Local\Temp"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.gumtreediff.gen.ExternalProcessTreeGenerator.readStandardOutput(ExternalProcessTreeGenerator.java:33)
	at com.github.gumtreediff.gen.srcml.AbstractSrcmlTreeGenerator.generate(AbstractSrcmlTreeGenerator.java:54)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromReader(TreeGenerator.java:37)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromFile(TreeGenerator.java:43)
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:43)
	at GumTreeDiff.diff(GumTreeDiff.java:59)
	at GumTreeDiff.main(GumTreeDiff.java:205)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 7 more
```
The main issue is the first line. I guess it tries to call "srcml" from under directory.
And, I moved Srcml.exe file under this directory. But, it still complains about it.

Could you let me know how to solve this issue? I was thinking about changing the code inside gumtree to find a correct path, but I am not familiar with gumtree code yet..

**Comment by ChunghaSung** [comment]
Oh, it works now after copying the entire directory of srcml.

**Comment by milahu** [comment]
just had the same problem

```
$ gumtree textdiff a.cc b.cc
Error while running client 'textdiff'.
java.io.IOException: Cannot run program "srcml" (in directory "/tmp"): error=2, No such file or directory
```

fix: add [srcml](https://github.com/srcML/srcML) to PATH

[gen.srcml/build.gradle](https://github.com/GumTreeDiff/gumtree/blob/main/gen.srcml/build.gradle)

```
description = 'GumTree tree generator for C/C++, C# and Java code. Requires srcml.'
```
