### ISSUE TITLE
 Cannot run program "pythonparser"

### ISSUE THREAD

**Issue by njuxc** [GumTreeDiff/gumtree#152]
I got an error when using gumtree for python in linux:

java.io.IOException: Cannot run program "pythonparser" (in directory "/tmp"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.gumtreediff.gen.ExternalProcessTreeGenerator.readStandardOutput(ExternalProcessTreeGenerator.java:34)
	at com.github.gumtreediff.gen.python.PythonTreeGenerator.generate(PythonTreeGenerator.java:61)
	at com.github.gumtreediff.gen.TreeGenerator.generateTree(TreeGenerator.java:38)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.reader(TreeGenerator.java:77)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:65)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:69)
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:43)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.getTreeContext(AbstractDiffClient.java:133)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.getSrcTreeContext(AbstractDiffClient.java:119)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.matchTrees(AbstractDiffClient.java:114)
	at com.github.gumtreediff.client.diff.TextDiff.run(TextDiff.java:98)
	at com.github.gumtreediff.client.Run.startClient(Run.java:80)
	at com.github.gumtreediff.client.Run.main(Run.java:108)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 13 more
** Error while running client diff: java.lang.NullPointerException

what can i do to fix it?
thanks!

**Comment by jrfaller** [comment]
Hi and thanks for your report.

You can install it from here : https://github.com/GumTreeDiff/pythonparser

Cheers!

**Comment by jrfaller** [comment]
I have updated the Getting Started page so that it's easier to know!

**Comment by Amirhgh74** [comment]
@njuxc hi 

how did you fix this? I am having the same issue with my code

**Comment by njuhxc** [comment]
> @njuxc hi
> 
> how did you fix this? I am having the same issue with my code

hi, i have solved the issue by using following steps:
cd pythonparser/
pip install -r requirement.txt 
cp pythonparser /tmp
PATH=$PATH:/tmp

**Comment by jrfaller** [comment]
Yes I believe this is indicated here : https://github.com/GumTreeDiff/pythonparser

**Comment by Amirhgh74** [comment]
> > @njuxc hi
> > how did you fix this? I am having the same issue with my code
> 
> hi, i have solved the issue by using following steps:
> cd pythonparser/
> pip install -r requirement.txt
> cp pythonparser /tmp
> PATH=$PATH:/tmp

Hi, thanks for your reply. I used these commands but I can't run the java code. 

I get this error after running the java code 

<img width="1045" alt="Screen Shot 2020-03-31 at 8 13 06 PM" src="https://user-images.githubusercontent.com/17717663/78046157-0bdefc00-738c-11ea-9f93-c75f471501e4.png">

anyone can help me with this? @njuxc @jrfaller

**Comment by jrfaller** [comment]
Is pythonparser working properly without gumtree? Try `pythonparser thefile.js`

**Comment by Amirhgh74** [comment]
@jrfaller 
Yes running python parser alone on a simple fine will return a result like this 

<img width="557" alt="Screen Shot 2020-03-31 at 8 18 35 PM" src="https://user-images.githubusercontent.com/17717663/78046758-cf5fd000-738c-11ea-8163-0ae945df804a.png">

**Comment by jrfaller** [comment]
OK it look likes a path problem to me, try to put a link to pythonparser somewhere like in /usr/bin ?

**Comment by Amirhgh74** [comment]
Thank you 
I am not sure why adding to the path with the command won't work but putting a link to usr/local/bin solved the problem

**Comment by jrfaller** [comment]
I think that there are some peculiarities w.r.t. the PATH computation on Mac OS if I remember correctly
