### ISSUE TITLE
Installing "pythonparser" [Question]

### ISSUE THREAD

**Issue by maldil** [GumTreeDiff/gumtree#153]
First of all thanks for the amazing tool!
I am trying to use gumtree  to identify diffs in Python files.
As mentioned in the **Getting Started** page, I am using following code snipe. 
```
String file1 = "./shapes1.py";
String file2 ="./shapes2.py";
ITree src = Generators.getInstance().getTree(file1).getRoot();
ITree dst = Generators.getInstance().getTree(file2).getRoot();
Matcher m = Matchers.getInstance().getMatcher(src, dst); // retrieve the default matcher
m.match();
ActionGenerator g = new ActionGenerator(src, dst, m.getMappings());
g.generate();
List<Action> actions = g.getActions(); // return the actions
System.out.println(actions);
```
I have following dependancies 
```
        <dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>client</artifactId>
            <version>2.1.2</version>
        </dependency>
            <dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>core</artifactId>
            <version>2.1.2</version>
        </dependency>
        <dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>gen.python</artifactId>
            <version>2.1.2</version>
        </dependency>
```
When I ran the the mentioned program, I received following error.
```
Exception in thread "main" java.io.IOException: Cannot run program "pythonparser" (in directory "/var/folders/45/_6kjfw9n0r0000gn/T"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.github.gumtreediff.gen.ExternalProcessTreeGenerator.readStandardOutput(ExternalProcessTreeGenerator.java:33)
	at com.github.gumtreediff.gen.python.PythonTreeGenerator.generate(PythonTreeGenerator.java:58)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromReader(TreeGenerator.java:37)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromFile(TreeGenerator.java:43)
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:43)
	at MainDiff.main(MainDiff.java:33)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:339)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:270)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
```

Steps 
1. I ran the executable [file](https://github.com/GumTreeDiff/pythonparser) in Mac OS.
This was not successful and got following error.  
```
ImportError: No module named asttokens
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...472 completed.
```
Then, I installed _asttokens_ and re ran. Finally I am receiving following error.
```
text = open(sys.argv[1], "r+").read()
IndexError: list index out of range
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```
I am not sure, whether I am following correct instructions. 
Could you please help me to solve this error and obtain python ast diff successfully ?
Is there a way to provide `gt.pp.path`programmically ?

**Comment by maldil** [comment]
I used, 
`System.setProperty("gt.pp.path", "./pythonparser");`
and I am not receiving any exception now. Instead, I am getting `INS 78694@@3 to 2092670@@ at 2` as an output.
If this is the correct way of using `pythonparser`, you may close this ticket. 
Thanks a lot!

**Comment by jrfaller** [comment]
Hi and thank you very much for your report!

The missing step in getting started is that I have to add "pip install asttokens" ?

Beware that the python AST generator is early stages and lack tests.

**Comment by maldil** [comment]
Thanks for the early warning. 
I am using Gumtree for large scale python projects analysis and I am sure Gumtree will help me a lot.
