### ISSUE TITLE
RuntimeException when building ITree of Python File

### ISSUE THREAD

**Issue by maldil** [GumTreeDiff/gumtree#154]
Hi,
I am trying to get Edit actions in commits of Python projects. I tested my code with couple of python files and I could get Edits successfully. 

But when I try to get `ITree` of attached python file it fires an exception as mentioned below. 

Python File = https://drive.google.com/open?id=1Ul9suAbRmCl13wPyn13dyK2XT314uZlC

Exception fires at
`ITree src = Generators.getInstance().getTree(path_s.toString()).getRoot();  \\path_s is path to the attached file`

Exception 
```
Exception in thread "main" java.lang.RuntimeException: 
	at com.github.gumtreediff.gen.ExternalProcessTreeGenerator.readStandardOutput(ExternalProcessTreeGenerator.java:41)
	at com.github.gumtreediff.gen.python.PythonTreeGenerator.generate(PythonTreeGenerator.java:58)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromReader(TreeGenerator.java:37)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromFile(TreeGenerator.java:43)
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:43)
	at MainDiff.getEditActions(MainDiff.java:98)
	at MainDiff.main(MainDiff.java:50)
```

My dependancies 
```
<dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>client</artifactId>
            <version>2.1.2</version>
        </dependency>
            <dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>core</artifactId>
            <version>2.1.2</version>
        </dependency>
        <dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>gen.python</artifactId>
            <version>2.1.2</version>
        </dependency>
```
Any help to get rid of above error is really appreciated.

**Comment by maldil** [comment]
@jrfaller do you have any idea about this? Thanks a lot!

**Comment by jrfaller** [comment]
Hi!

By using directly pythonparser on your file, I get the following error message :

```
Traceback (most recent call last):
  File "/Users/falleri/.local/bin/pythonparser", line 30, in <module>
    astTok = asttokens.ASTTokens(source, parse=True)
  File "/usr/local/lib/python2.7/site-packages/asttokens/asttokens.py", line 47, in __init__
    self._tree = ast.parse(source_text, filename) if parse else tree
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 8
    def load_dataset_at(index) -> (np.array, np.array):
                               ^
SyntaxError: invalid syntax
```
