### ISSUE TITLE
gumtree docker git misconfiguration

### ISSUE THREAD

**Issue by boneskull** [GumTreeDiff/gumtree#195]
I'm on macOS 10.15.7 and using Git 2.28.0.  Per [the wiki](https://github.com/GumTreeDiff/gumtree/tree/develop/docker), I've downloaded a gumtree docker image, and I added this to my `.gitconfig`:

```ini
[difftool "gumtree-docker"]
  cmd = docker run -v /private/$REMOTE:/diff/left -v /private/$LOCAL:/diff/right -p 4567:4567 gumtreediff/gumtree webdiff left/ right/
```

I have some changes in my working copy:

```shell
$ git status -s
 M test/integration/diffs.spec.js
 M test/integration/fixtures/diffs/diffs.fixture.js
 M test/integration/no-diff.spec.js
```

I try to use `git difftool` directly:

```shell
$ git difftool -d -t gumtree-docker
java.nio.file.NoSuchFileException: left/test/integration/no-diff.spec.js
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.nio.file.Files.size(Files.java:2380)
	at com.github.gumtreediff.io.DirectoryComparator.hasChanged(DirectoryComparator.java:136)
	at com.github.gumtreediff.io.DirectoryComparator.compare(DirectoryComparator.java:102)
	at com.github.gumtreediff.client.diff.webdiff.WebDiff.run(WebDiff.java:81)
	at com.github.gumtreediff.client.Run.startClient(Run.java:80)
	at com.github.gumtreediff.client.Run.main(Run.java:110)
Starting server: http://127.0.0.1:4567
```

What am I missing here?  I do not have any directories named `left/` or `right/` as in the configuration...

**Comment by jrfaller** [comment]
Hi!

It has been some time since I last tried and I have the same problem. Left and right folders are folder on the container that are  bound to folder on the host via the `-v` in the command. However file binding seems to cause a problem to java nio...

**Comment by jrfaller** [comment]
OK this was a tricky one. Git diff by default make symlinks to the working copy folder, but these symlinks obviously do not work anymore inside the container. Therefore, the git difftool command must be used like this `git difftool -d --no-symlinks -t gumtree-docker`. Notice the `--no-symlinks` that does all the job 😄.

Cheers!

**Comment by boneskull** [comment]
thanks, will try it!
