### ISSUE TITLE
Java Exception when run parse

### ISSUE THREAD

**Issue by hebit** [GumTreeDiff/gumtree#211]
Hi,

I downloaded the zip file from the [last release (v2.1.2)](https://github.com/GumTreeDiff/gumtree/releases/tag/v2.1.2) and i extracted it into a folder and then i ran the binary file using the `parse` client (as described in [wiki](https://github.com/GumTreeDiff/gumtree/wiki/Clients#parse)).

---  
The input file was the following code: 
```c
#include <stdio.h>
int main() {    

    int number1, number2, sum;
    
    printf("Enter two integers: ");
    scanf("%d %d", &number1, &number2);

    // calculating sum
    sum = number1 + number2;      
    
    printf("%d + %d = %d", number1, number2, sum);
    return 0;
}
```
The script used in terminal: 
```shell
./gumtree parse input.c
```
But the output was:
```
java.lang.NumberFormatException: For input string: "Program"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.github.gumtreediff.io.TreeIoUtils$XmlInternalGenerator.generate(TreeIoUtils.java:646)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromReader(TreeGenerator.java:37)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromString(TreeGenerator.java:55)
	at com.github.gumtreediff.gen.c.CTreeGenerator.generate(CTreeGenerator.java:58)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromReader(TreeGenerator.java:37)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromFile(TreeGenerator.java:43)
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:43)
	at com.github.gumtreediff.client.Serializer.getTreeContext(Serializer.java:145)
	at com.github.gumtreediff.client.Serializer.run(Serializer.java:131)
	at com.github.gumtreediff.client.Run.startClient(Run.java:80)
	at com.github.gumtreediff.client.Run.main(Run.java:108)
java.lang.NullPointerException
```

The [cgum](https://github.com/GumTreeDiff/cgum) was already installed and the Java version on my machine (ubuntu 18.04) is 11.0.9.1

**Comment by hebit** [comment]
I tested `parse` using a C++ code and it worked.  But I need to use the `parse` with C code in my project.

--- 
Input file: 
```cpp

#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}

```
The script:
```shell
./gumtree parse test.cpp
```
And the output was:
```
{
	"root": {
		"type": "3594628",
		"typeLabel": "unit",
		"children": [
			{
				"type": "1942574248",
				"typeLabel": "include",
				"children": [
					{
						"type": "-962590641",
						"typeLabel": "directive",
						"children": []
					},
					{
						"type": "3143036",
						"typeLabel": "file",
						"children": []
					}
				]
			},
			{
				"type": "1380938712",
				"typeLabel": "function",
				"children": [
					{
						"type": "3575610",
						"typeLabel": "type",
						"children": [
							{
								"type": "3373707",
								"label": "int",
								"typeLabel": "name",
								"children": []
							}
						]
					},
					{
						"type": "3373707",
						"label": "main",
						"typeLabel": "name",
						"children": []
					},
					{
						"type": "1133090676",
						"typeLabel": "parameter_list",
						"children": []
					},
					{
						"type": "93832333",
						"typeLabel": "block",
						"children": [
							{
								"type": "1384891079",
								"typeLabel": "block_content",
								"children": [
									{
										"type": "490731474",
										"typeLabel": "expr_stmt",
										"children": [
											{
												"type": "3127797",
												"typeLabel": "expr",
												"children": [
													{
														"type": "3373707",
														"typeLabel": "name",
														"children": [
															{
																"type": "3373707",
																"label": "std",
																"typeLabel": "name",
																"children": []
															},
															{
																"type": "-500553564",
																"label": "::",
																"typeLabel": "operator",
																"children": []
															},
															{
																"type": "3373707",
																"label": "cout",
																"typeLabel": "name",
																"children": []
															}
														]
													},
													{
														"type": "-500553564",
														"label": "<<",
														"typeLabel": "operator",
														"children": []
													},
													{
														"type": "182460591",
														"label": "\"Hello World!\"",
														"typeLabel": "literal",
														"children": []
													}
												]
											}
										]
									},
									{
										"type": "-934396624",
										"typeLabel": "return",
										"children": [
											{
												"type": "3127797",
												"typeLabel": "expr",
												"children": [
													{
														"type": "182460591",
														"label": "0",
														"typeLabel": "literal",
														"children": []
													}
												]
											}
										]
									}
								]
							}
						]
					}
				]
			}
		]
	}
}
```

**Comment by jrfaller** [comment]
I think your problem is due to the fact you use the version 2.1.2 of GumTree while cgum have been changed to work with the upcoming version 3.0.0. Two choices : you upgrade to the last commit (or try the docker image) or you downgrade cgum to the previous version. I'll try to post a release of 3.0.0-beta1 soon 😉

**Comment by hebit** [comment]
Okay!
@jrfaller thank you a lot!
