### ISSUE TITLE
Use gumtree on C files -- cannot run 'cgum'

### ISSUE THREAD

**Issue by saheel1115** [GumTreeDiff/gumtree#23]
Hello! I am trying to use Gumtree to diff 2 C files. I followed the steps in the Getting Started page but I get an error (pasted below). Using Gumtree on 2 Java files works just fine. From what I can understand, it is unable to locate and run "cgum". Can someone help me resolve the problem? Is there any other way of using Gumtree on C files? I am not experienced in Java hence don't know where to start.

The command I used was ```gumtree diff a.c b.c```

```
java.io.IOException: Cannot run program "cgum" (in directory "/tmp"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.gumtreediff.gen.c.CTreeGenerator.generate(CTreeGenerator.java:72)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromReader(TreeGenerator.java:32)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromFile(TreeGenerator.java:38)
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:48)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.getTreeContext(AbstractDiffClient.java:125)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.getSrcTreeContext(AbstractDiffClient.java:113)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.matchTrees(AbstractDiffClient.java:105)
	at com.github.gumtreediff.client.diff.TextDiff.run(TextDiff.java:98)
	at com.github.gumtreediff.client.Run.startClient(Run.java:89)
	at com.github.gumtreediff.client.Run.main(Run.java:117)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 10 more
** Error while running client diff: java.lang.NullPointerException
```

**Comment by saheel1115** [comment]
Okay, looks like cgum is the tool found in gumtreediff/cgum. Unfortunately, I couldn't compile that repository to get the cgum binary. I have opened an issue there regarding that. Once I have that binary, to avoid the above error is it sufficient to include the cgum executable in my path?

**Comment by jrfaller** [comment]
Yes you are right!

I believe this should go to the Wiki :)

In which section do you think it would be appropriate?

**Comment by JuliaLawall** [comment]
On Fri, 19 Aug 2016, Jean-Rémy Falleri wrote:

>
> Yes you are right!
>
> I believe this should go to the Wiki :)
>
> In which section do you think it would be appropriate?

I'm lost.  There is a comment in saheel1115's mail about "Unfortunately,
I couldn't compile that repository to get the cgum binary. I have opened
an issue there regarding that."  But I don't know how to find the issue
that he opened.

julia

**Comment by jrfaller** [comment]
I believe this is this one : https://github.com/GumTreeDiff/cgum/issues/1

**Comment by saheel1115** [comment]
I was able to install Cgum and successfully parse/diff C files. Thanks!

> In which section do you think it would be appropriate?

The Installation section in Getting Started mentions that Gradle is used to manage dependencies. Ideally, Gradle should deal with Cgum internally. If that cannot be done or is a time-consuming task, at the very least we can add a line in the Installation section saying Gumtree/Cgum is a dependency (and that the binary should be in the path) if you want to diff C files.

**Comment by jrfaller** [comment]
I have updated the installation section of the wiki!

**Comment by nimisha-agarwal** [comment]
I have added "cgum" to the system path, however, I am still getting the same error. Can someone help me to resolve the error?
java.io.IOException: Cannot run program "cgum" (in directory "/tmp"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.gumtreediff.gen.c.CTreeGenerator.generate(CTreeGenerator.java:73)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromReader(TreeGenerator.java:37)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromFile(TreeGenerator.java:43)
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:43)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.getTreeContext(AbstractDiffClient.java:128)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.getSrcTreeContext(AbstractDiffClient.java:114)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.matchTrees(AbstractDiffClient.java:105)
	at com.github.gumtreediff.client.diff.TextDiff.run(TextDiff.java:98)
	at com.github.gumtreediff.client.Run.startClient(Run.java:80)
	at com.github.gumtreediff.client.Run.main(Run.java:108)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 10 more
** Error while running client diff: java.lang.NullPointerException
