### ISSUE TITLE
SyntaxException when parse or diff big python file!

### ISSUE THREAD

**Issue by KingGoldXu** [GumTreeDiff/gumtree#231]
Hi, I'm using gumtree to process a large amount of python code.
I got a SyntaxException when parse or diff **big** python files.
```
gumtree parse 0e470ca468870bb605c8171bf169df9406c52e05^a^glance^tests^unit^v1^test_api.py
Error while running client 'parse'.
com.github.gumtreediff.gen.SyntaxException
        at com.github.gumtreediff.gen.ExternalProcessTreeGenerator.readStandardOutput(ExternalProcessTreeGenerator.java:43)
        at com.github.gumtreediff.gen.python.PythonTreeGenerator.generate(PythonTreeGenerator.java:37)
        at com.github.gumtreediff.gen.TreeGenerator.generateTree(TreeGenerator.java:41)
        at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.reader(TreeGenerator.java:119)
        at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:90)
        at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:100)
        at com.github.gumtreediff.gen.TreeGenerators.getTree(TreeGenerators.java:55)
        at com.github.gumtreediff.gen.TreeGenerators.getTree(TreeGenerators.java:67)
        at com.github.gumtreediff.client.Serializer.getTreeContext(Serializer.java:140)
        at com.github.gumtreediff.client.Serializer.run(Serializer.java:132)
        at com.github.gumtreediff.client.Run.startClient(Run.java:81)
        at com.github.gumtreediff.client.Run.main(Run.java:115)
```
file attached!  [example1.zip](https://github.com/GumTreeDiff/gumtree/files/6201643/example1.zip)

It's ok when I run `pythonparser 0e470ca468870bb605c8171bf169df9406c52e05^a^glance^tests^unit^v1^test_api.py` directly.
To be clear, I used `#!/usr/bin/env python2` if you did not make it.

The exception was thrown by `readStandardOutput`:
```
    public String readStandardOutput(Reader r) throws IOException {
        // TODO avoid recreating file if supplied reader is already a file
        File f = dumpReaderInTempFile(r);
        ProcessBuilder b = new ProcessBuilder(getCommandLine(f.getAbsolutePath()));
        b.directory(f.getParentFile());
        Process p = b.start();
        try (BufferedReader br = new BufferedReader(
                new InputStreamReader(p.getInputStream(), StandardCharsets.UTF_8))) {
            StringBuilder buf = new StringBuilder();
            String line = null;
            while ((line = br.readLine()) != null)
                buf.append(line + System.lineSeparator());
            p.waitFor();
            if (p.exitValue() != 0)
                throw new SyntaxException(this, r, null);
            r.close();
            p.destroy();
            return buf.toString();
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        } finally {
            f.delete();
        }
    }
```

**Comment by jrfaller** [comment]
HI!

I cannot reproduce the problem. `gumtree parse f` and `gumtree webdiff f f` with f being `0e470ca468870bb605c8171bf169df9406c52e05^a^glance^tests^unit^v1^test_api.py` are working for me 😢 
However I run everything with `python3`we do not support `python2` anymore.

Cheers.

**Comment by KingGoldXu** [comment]
Thank!
I tried it myself, It did word well with python3.
