### ISSUE TITLE
ConcurrentModificationException when comparing XML files

### ISSUE THREAD

**Issue by Symbolk** [GumTreeDiff/gumtree#232]
I build a gumtree.jar with the latest version, and use the following command to compare two versions of a XML file from an Android project (https://github.com/UnevenSoftware/LeafPic/commit/ea5ccf3#diff-998c3117acad3fd8021869d6e35eb5ddef55e484adac24626b8f77ff1b82a70d):

```
java -jar gumtree.jar swingdiff a.xml b.xml
```
But it reports error when parsing the XML to tree, here is the output:

```
Starting server: http://127.0.0.1:4567.
cd /Users/symbolk/Desktop
line 1:1 no viable alternative at character '?'
line 1:36 no viable alternative at character '?'
line 60:0 mismatched input '<EOF>' expecting TAG_END_OPEN
[qtp969602112-20] ERROR spark.http.matching.GeneralError -
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.github.gumtreediff.tree.TreeUtils$3.next(TreeUtils.java:201)
	at com.github.gumtreediff.tree.TreeUtils$3.next(TreeUtils.java:185)
	at com.github.gumtreediff.gen.antlr3.xml.XmlTreeGenerator.generate(XmlTreeGenerator.java:45)
	at com.github.gumtreediff.gen.TreeGenerator.generateTree(TreeGenerator.java:41)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.reader(TreeGenerator.java:119)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:90)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:100)
	at com.github.gumtreediff.gen.TreeGenerators.getTree(TreeGenerators.java:55)
	at com.github.gumtreediff.gen.TreeGenerators.getTree(TreeGenerators.java:67)
	at com.github.gumtreediff.actions.Diff.compute(Diff.java:79)
	at com.github.gumtreediff.client.diff.AbstractDiffClient.getDiff(AbstractDiffClient.java:124)
	at com.github.gumtreediff.client.diff.webdiff.WebDiff.lambda$configureSpark$3(WebDiff.java:112)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1671)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

And here is the files:

[files.zip](https://github.com/GumTreeDiff/gumtree/files/6201700/files.zip)

**Comment by jrfaller** [comment]
Hi!

A first note is that the XML parser is not good at all unfortunately. It is based on an Antlr3 grammar which has not been used in production. I wanted to make a better backend but afaik no traditional XML parser provide the exact character location of AST nodes 😢 

Here I suspect the problem comes from the fact that the XML parser crashes, which leaks to the CLI. You could try a simple `gumtree parse` on the file. However it would be nice if the error message was more "graceful". Cheers.

**Comment by Symbolk** [comment]
Hi @jrfaller , I think I have located the error, apparently, it is caused by calling `remove()` while looping with iterator, which leads to unequal of `expectedModCount` and `modCount `.

Specifically, here in the loop: 

https://github.com/GumTreeDiff/gumtree/blob/c7536bccbe4509aebcd887dfb7c4244eea85b34e/gen.antlr3-xml/src/main/java/com/github/gumtreediff/gen/antlr3/xml/XmlTreeGenerator.java#L45-L49

`setParentAndUpdateChildren` is called, which changes the iterable List by removing one of its children:

https://github.com/GumTreeDiff/gumtree/blob/c7536bccbe4509aebcd887dfb7c4244eea85b34e/core/src/main/java/com/github/gumtreediff/tree/AbstractTree.java#L62

For resolution, could we have a (deep) copy of the iterable List to use in the for loop, and override the original one after pruning?

**Comment by jrfaller** [comment]
Well spotted!

Here in this case, I think the easiest way is to put every selected `c` in a temp list and then process the temp list to `setParentAndUpdateChildren(null)` no?

**Comment by Symbolk** [comment]
> Well spotted!
> 
> Here in this case, I think the easiest way is to put every selected `c` in a temp list and then process the temp list to `setParentAndUpdateChildren(null)` no?

Yeah, you are really right, created a pr for this.
