### ISSUE TITLE
"Back" button crashes webdiff

### ISSUE THREAD

**Issue by csiefer2** [GumTreeDiff/gumtree#245]
Running gumtree on Windows + cygwin and and diff-ing C++ files yields the following crash / backtrace when I press the back button:

```
$ gumtree webdiff v1.cpp v3.cpp
Starting server: http://127.0.0.1:4567.
[qtp1700211643-22] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.relativize(java.nio.file.Path)" because the return value of "com.github.gumtreediff.io.DirectoryComparator.getSrc()" is null
        at com.github.gumtreediff.client.diff.webdiff.DirectoryDiffView$ModifiedFiles.renderOn(DirectoryDiffView.java:117)
        at org.rendersnake.HtmlCanvas.render(HtmlCanvas.java:277)
        at org.rendersnake.HtmlCanvas.render_if(HtmlCanvas.java:289)
        at com.github.gumtreediff.client.diff.webdiff.DirectoryDiffView.renderOn(DirectoryDiffView.java:65)
        at com.github.gumtreediff.client.diff.webdiff.WebDiff.render(WebDiff.java:152)
        at com.github.gumtreediff.client.diff.webdiff.WebDiff.lambda$configureSpark$1(WebDiff.java:100)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1671)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:505)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

Browser is Firefox on Windows.

**Comment by jrfaller** [comment]
Hi @csiefer2 !

A quick note, running GumTree on C++ code requires the installation of srcML. Also, for convenience, you can try GumTree using our Docker container that might ease the installation process.

Regarding your bug, it seems to be caused by a path set to null somewhere in the process, probably this line `this.src = this.src.getParent();`, but I cannot reproduce the problem since I do not have access to a Windows machine 😢 

Cheers!

**Comment by jrfaller** [comment]
Quick question, looking at your command you ask for a between file diff, the lead normally to a single view presenting the diff. In this mode, the back button should be deactivated as it serves no purpose. This is therefore a usability bug. Thanks for spotting it!
