### ISSUE TITLE
Use gumtree API in IntelliJ on Windows

### ISSUE THREAD

**Issue by ztwater** [GumTreeDiff/gumtree#275]
I have added tree-sitter-parser.py to my system path and it could run from cmd. But when I called the API (e.g. JavaTreeSitterTreeGenerator().generateFrom().file(file); ) from IDE or from commands like "gumtree..." I got this error:

```
java.io.IOException: Cannot run program "tree-sitter-parser.py" (in directory "C:\Users\24426\AppData\Local\Temp"): CreateProcess error=193, %1 is not a valid Win32 application
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
at com.github.gumtreediff.gen.ExternalProcessTreeGenerator.readStandardOutput(ExternalProcessTreeGenerator.java:35)
at com.github.gumtreediff.gen.treesitter.AbstractTreeSitterGenerator.generate(AbstractTreeSitterGenerator.java:37)
at com.github.gumtreediff.gen.TreeGenerator.generateTree(TreeGenerator.java:41)
at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.reader(TreeGenerator.java:119)
at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:90)
at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:100)
```

Could you please tell me how to solve this error? I guess processbuilder has something to do with the OS...

**Comment by jrfaller** [comment]
Hi!

I guess the shebang `#!/usr/bin/env python` does not work on Windows 😄 

However I don't know how to get a Python file running, but if you manage to make a `bat` file don't hesitate to make a PR!

Cheers.

**Comment by ztwater** [comment]
Thanks a lot! I found that `ProcessBuilder` can not direct run python scripts, so I changed the arguments of `getCommandLine()` in `AbstractTreeSitterGenerator.java` (see [here](https://stackoverflow.com/questions/44845041/run-python-script-from-java-code)). It is running now but a parse error occurs in `TreeIoUtils.java`.

```
while (r.hasNext()) {
    XMLEvent e = r.nextEvent();
    if (e instanceof StartElement) {
```
```
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
	at java.xml/com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
	at com.github.gumtreediff.io.TreeIoUtils$XmlInternalGenerator.generate(TreeIoUtils.java:784)
	at com.github.gumtreediff.gen.TreeGenerator.generateTree(TreeGenerator.java:41)
        ...
```

**Comment by ztwater** [comment]
By the way, how can I use tree-sitter-parser as my backend when using cmd? 

Thanks for your reply!

**Comment by jrfaller** [comment]
OK strange, the XML your parsed seems correct
