### ISSUE TITLE
SyntaxException error when parse C file

### ISSUE THREAD

**Issue by Yuuoniy** [GumTreeDiff/gumtree#276]
Hi, I'm using gumtree to parse C file. 
I got a SyntaxException when parse a normal C file.
```
root@e98ac109afb4:/opt/tree-sitter-parser# gumtree parse /diff/left/f153546913ba_0.c 
Error while running client 'parse'.
com.github.gumtreediff.gen.SyntaxException: java.lang.IllegalArgumentException: Syntax error at pos: 38257
        at com.github.gumtreediff.gen.treesitter.AbstractTreeSitterGenerator.generate(AbstractTreeSitterGenerator.java:43)
        at com.github.gumtreediff.gen.TreeGenerator.generateTree(TreeGenerator.java:41)
        at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.reader(TreeGenerator.java:119)
        at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:90)
        at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:100)
        at com.github.gumtreediff.gen.TreeGenerators.getTree(TreeGenerators.java:73)
        at com.github.gumtreediff.client.ParseClient.getTreeContext(ParseClient.java:63)
        at com.github.gumtreediff.client.ParseClient.run(ParseClient.java:54)
        at com.github.gumtreediff.client.Run.startClient(Run.java:94)
        at com.github.gumtreediff.client.Run.main(Run.java:128)
Caused by: java.lang.IllegalArgumentException: Syntax error at pos: 38257
        ... 10 more
```
And I tried 
```
/opt/tree-sitter-parser.py /diff/left/f153546913ba_0.c c
```
It works well.
file: [f153546913ba_0.zip](https://github.com/GumTreeDiff/gumtree/files/8349055/f153546913ba_0.zip)
I use the docker envirnment of gumtree. 
Do you have any idea? Thanks.

**Comment by Yuuoniy** [comment]
After test, I found the following code slice result in the error
```
static const struct net_device_ops ice_netdev_ops = {
#ifdef CONFIG_RFS_ACCEL
	.ndo_rx_flow_steer = ice_rx_flow_steer,
#endif
	.ndo_tx_timeout = ice_tx_timeout,
};
```
But I wonder why tree-sitter-parse handle it normally but gumtree bails out.

**Comment by jrfaller** [comment]
Hi!

This is strange, could you inspect the XML produced by `tree-sitter-parser` to check if everything's alright?

Cheers.

**Comment by Yuuoniy** [comment]
Oh It has nodes which type are ERROR 
```xml
  <tree type="ERROR" pos="54" length="6">
                                        <tree type="#ifdef" pos="54" length="6" label="#ifdef"/>
                                </tree>
<tree type="ERROR" pos="119" length="6">
                                        <tree type="#endif" pos="119" length="6" label="#endif"/>
                                </tree>
```
code :
```
static const struct net_device_ops ice_netdev_ops = {
#ifdef CONFIG_RFS_ACCEL
	.ndo_rx_flow_steer = ice_rx_flow_steer,
#endif
};
```
Following is the whole XML:
```xml
<?xml version="1.0" ?>
<tree type="translation_unit" pos="0" length="129">
        <tree type="declaration" pos="0" length="128">
                <tree type="storage_class_specifier" pos="0" length="6">
                        <tree type="static" pos="0" length="6" label="static"/>
                </tree>
                <tree type="type_qualifier" pos="7" length="5">
                        <tree type="const" pos="7" length="5" label="const"/>
                </tree>
                <tree type="struct_specifier" pos="13" length="21">
                        <tree type="struct" pos="13" length="6" label="struct"/>
                        <tree type="type_identifier" pos="20" length="14" label="net_device_ops"/>
                </tree>
                <tree type="init_declarator" pos="35" length="92">
                        <tree type="identifier" pos="35" length="14" label="ice_netdev_ops"/>
                        <tree type="=" pos="50" length="1" label="="/>
                        <tree type="initializer_list" pos="52" length="75">
                                <tree type="{" pos="52" length="1" label="{"/>
                                <tree type="ERROR" pos="54" length="6">
                                        <tree type="#ifdef" pos="54" length="6" label="#ifdef"/>
                                </tree>
                                <tree type="assignment_expression" pos="61" length="56">
                                        <tree type="field_expression" pos="61" length="36">
                                                <tree type="identifier" pos="61" length="16" label="CONFIG_RFS_ACCEL"/>
                                                <tree type="." pos="79" length="1" label="."/>
                                                <tree type="field_identifier" pos="80" length="17" label="ndo_rx_flow_steer"/>
                                        </tree>
                                        <tree type="=" pos="98" length="1" label="="/>
                                        <tree type="identifier" pos="100" length="17" label="ice_rx_flow_steer"/>
                                </tree>
                                <tree type="," pos="117" length="1" label=","/>
                                <tree type="ERROR" pos="119" length="6">
                                        <tree type="#endif" pos="119" length="6" label="#endif"/>
                                </tree>
                                <tree type="}" pos="126" length="1" label="}"/>
                        </tree>
                </tree>
                <tree type=";" pos="127" length="1" label=";"/>
        </tree>
</tree>
```

**Comment by Yuuoniy** [comment]
similar cases:
```
static int __init acpi_pm_good_setup(char *__str)
{
	acpi_pm_good = 1;
	return 1;
}
```
The XML has ERROR node:
```
  <tree type="ERROR" pos="30" length="6">
                                <tree type="identifier" pos="30" length="6" label="__init"/>
                        </tree>
```
Gumtree fail to handle this. But this situation are quiet common in kernel driver code.
Maybe gumtree could skip ERROR nodes.

**Comment by jrfaller** [comment]
Hi!

Thanks for the analysis.

Error nodes are the one returned by tree-sitter when there is a parse error, that's why when receiving such a node, GumTree raises an error.

Maybe you could make one that ignores those for your use case?

**Comment by Yuuoniy** [comment]
I will do. Thanks for your reply.
