### ISSUE TITLE
parse go throw ClassCastException

### ISSUE THREAD

**Issue by yikengboy** [GumTreeDiff/gumtree#362]
when I use  gen.treesitter-ng parse go file, throw ClassCastException.
The complete exception stack is as follows:
`Exception in thread "main" java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
	at com.github.gumtreediff.gen.treesitterng.AbstractTreeSitterNgGenerator.tsNode2GumTree(AbstractTreeSitterNgGenerator.java:171)
	at com.github.gumtreediff.gen.treesitterng.AbstractTreeSitterNgGenerator.generateFromTreeSitterTree(AbstractTreeSitterNgGenerator.java:199)
	at com.github.gumtreediff.gen.treesitterng.AbstractTreeSitterNgGenerator.generate(AbstractTreeSitterNgGenerator.java:59)
	at com.github.gumtreediff.gen.TreeGenerator.generateTree(TreeGenerator.java:41)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.reader(TreeGenerator.java:119)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:90)
	at com.github.gumtreediff.gen.TreeGenerator$ReaderConfigurator.file(TreeGenerator.java:100)
	at com.github.gumtreediff.gen.TreeGenerators.getTree(TreeGenerators.java:58)
	at com.qunhe.devops.ast.analysis.biz.demo.main(demo.java:30)`

After debugging, I found that it was caused by forcibly converting an empty List into a Map.
![image](https://github.com/user-attachments/assets/278da512-5d01-4a48-b6a7-c99920de9f02)
![image](https://github.com/user-attachments/assets/4366f03e-14d1-4dd3-bb84-66de1755e7f7)
Is this a bug?

**Comment by jrfaller** [comment]
Hi, and thanks a lot for the report!

This is definitively a bug :-) Normally `aliased` configuration is given using a Yaml dictionary. However, when there is no configuration, I used an empty list that worked fine in Python but not in Java where there is a static type error.

Maybe the way to go is to not have the `aliased` configuration when it's empty?

Cheers.

**Comment by lyoubo** [comment]
When I use the latest version of gumtree (4.0.0-beta3), parsing go language files still throws a ClassCastException. Can you try to fix this and at least get GumTree working properly?

![Uploading exception.PNG…]()
