### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space analyzing php file with gen-antlr.php

### ISSUE THREAD

**Issue by onhate** [GumTreeDiff/gumtree#53]
Hi there, I think there is a bug while analyzing this php file, do you think it is related to the fact that it has html and php in the same file?

```java
Generators.getInstance().getTree("404.php")
```

the exception

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at org.antlr.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:146)
	at org.antlr.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:137)
	at org.antlr.runtime.CommonTokenStream.consume(CommonTokenStream.java:71)
	at org.antlr.runtime.DFA.predict(DFA.java:120)
	at com.github.gumtreediff.gen.php.PhpParser.statement(PhpParser.java:309)
	at com.github.gumtreediff.gen.php.PhpParser.prog(PhpParser.java:231)
	at com.github.gumtreediff.gen.php.PhpTreeGenerator.getStartSymbol(PhpTreeGenerator.java:41)
	at com.github.gumtreediff.gen.antlr.AbstractAntlrTreeGenerator.generate(AbstractAntlrTreeGenerator.java:56)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromReader(TreeGenerator.java:32)
	at com.github.gumtreediff.gen.TreeGenerator.generateFromFile(TreeGenerator.java:38)
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:43)
```

the content of the file to be analyzed

```php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>404 - Not Found</title>

	<link href='http://fonts.googleapis.com/css?family=Ubuntu&amp;subset=latin' rel='stylesheet' type='text/css'>

	<style type="text/css">
		body {
			background-color: #fff;
			margin: 45px 0 0 0;
			font-family: 'Ubuntu', sans-serif;
			font-size: 16px;
			color: #3f3f3f;
		}

		h1 {
			font-size: 40px;
			margin: 0 0 10px 0;
		}

		a {
			color: #000;
		}

		#wrapper {
			width: 740px;
			margin: 0 auto;
		}

		#content {
			padding: 10px 10px 10px 10px;
			background-color: #ffebe8;
			border: 1px solid #dd3c10;
			border-radius: 10px;
		}
	</style>
</head>
<body>
	<div id="wrapper">
		<?php
			$messages = array('Should we ask for directions?', 'This doesn\'t look familiar.', 'We need a map.');
			$message = $messages[mt_rand(0, 2)];
		?>

		<h1><?php echo $message; ?></h1>

		<div id="content">
			The resource you requested was not found.
			<br /><br />
			Would you like go to our <a href="<?php echo System\Config::get('application.url'); ?>">home page</a> instead?
		</div>
	</div>
</body>
</html>
```

**Comment by onhate** [comment]
In the last part of php in this file, if I change this

```php
Would you like go to our <a href="<?php echo System\Config::get('application.url'); ?>">home page</a> instead?
```

with this

```php
Would you like go to our <a href="<?php echo SystemConfig::get('application.url'); ?>">home page</a> instead?
```

it works, I just replaced System\Config  with SystemConfig. Since the code I'm analyzing is not mine, do you think I can detect this with some kind of pre-validation of the PHP before running the analyzis?

**Comment by jrfaller** [comment]
Hi!

Unfortunately our PHP parser is based on a antlr grammar that does not seem to be actively maintained, therefore I guess there is not much I can do, maybe it would be best to use a more actively maintained parser, but I have no idea which one?

**Comment by indolering** [comment]
> maybe it would be best to use a more actively maintained parser, but I have no idea which one?

[Eclipse's PDT](https://www.eclipse.org/pdt/articles/ast/PHP_AST.html)?

**Comment by jrfaller** [comment]
Great idea!

**Comment by jrfaller** [comment]
Not easy to find a mavenized version of Eclipse PDT though :(

**Comment by indolering** [comment]
> Not easy to find a mavenized version of Eclipse PDT though :(

Ahh dependency hell!  If only Git had a sane versioning system and repo system built in.  IntelliJ appears to be using Flex for Python.
