### ISSUE TITLE
NoSuchMethodException when running wiki example, what do I need to import?

### ISSUE THREAD

**Issue by ttben** [GumTreeDiff/gumtree#81]
Hi there!

I wanted to do exactly what is specified [in the wiki](https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API#computing-the-actions-between-two-trees). Thus I started a new Java maven-project, added the following dependency

```
        <dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>core</artifactId>
            <version>2.1.0</version>
        </dependency>
```
and copy-pasted the example.

Then it states that `import com.github.gumtreediff.client.Run;` can't be resolved
Therefore I add the following dependency:
```
        <dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>client</artifactId>
            <version>2.1.0</version>
        </dependency>
```

Now it compiles but throw an expection at Runtime.

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.reflections.Reflections.<init>(Reflections.java:141)
	at com.github.gumtreediff.client.Run.initGenerators(Run.java:56)
	at com.github.gumtreediff.client.Run.<clinit>(Run.java:80)
	at Main.main(Main.java:14)
```
`Main#14` is `Run.initGenerators();`

Am I missing something in the doc? 
What are the needed dependencies to run this example?
Can I suggest to add these requirements to the wiki article itself?

Thanks!

**Comment by ttben** [comment]
A [quick search](https://github.com/ronmamo/reflections/issues/194) seems to indicate that Guava is the issue. I don't know how bypassing this.

**Comment by ttben** [comment]
Using custom generator, as proposed in the wiki, avoid the problem (but the sequence of actions is empty... but thats another issue ;) )
code run:
```
        //Run.initGenerators();
        String file1 = "/Users/benjaminbenni/Desktop/test-diff-gumtree/base/toto/ClassC.java";
        String file2 = "/Users/benjaminbenni/Desktop/test-diff-gumtree/right/toto/ClassD.java";
        ITree src  = new JdtTreeGenerator().generateFromString(file1).getRoot();
        ITree dst  = new JdtTreeGenerator().generateFromString(file2).getRoot();
        Matcher m = Matchers.getInstance().getMatcher(src, dst); // retrieve the default matcher
        m.match();
        ActionGenerator g = new ActionGenerator(src, dst, m.getMappings());
        g.generate();
        List<Action> actions = g.getActions(); // return the actions but this is empty
```

**Comment by jrfaller** [comment]
Mmm well spotted!

Don't know how to fix this problem though, it's annoying...

For the empty list of actions are there any differences between the two files?

**Comment by ttben** [comment]
The class name is different
I am not sure if anything more was changed (maybe an addition of Doc)
But still, webdiff returns something and this set of actions is empty
If I remember correcty the diffs option returned nothing BUT jsondiff worked.
I dont know if it can help. :)

**Comment by jrfaller** [comment]
Okay this is not normal...

Could you attach the two files?

**Comment by jrfaller** [comment]
Hi Ben!

Ok I understand better now. Directory comparison does not include renaming detection, unlike in Git, this must be the source of your problem, maybe it would be a cool feature to add.

**Comment by ttben** [comment]
Indeed :)
Then, how would you compare two directories in a Java code, using GumTree API, considering the initial runtime exception.
*ie.* instead of writing

```
        String base = Main.class.getClassLoader().getResource("base/toto/ClassC.java").getFile();
        String left = Main.class.getClassLoader().getResource("left/toto/ClassC.java").getFile();
```

writing
```
        String base = Main.class.getClassLoader().getResource("base/toto/").getFile();
        String left = Main.class.getClassLoader().getResource("left/toto/").getFile();
```

I expect this to yield a addition/deletion of class instead of a renaming :)

Thanks again!

**Comment by jrfaller** [comment]
If the file is detected as renamed, then I believe that class name renaming is the diff to go, else it would deletion / addition of a file.

The DirectoryComparator class is the abstraction you need to use to perform directory comparison.

**Comment by ttben** [comment]
Ok thank you for your quick answer.

Comparing the `base` and `right` folder yield an addition of `D` and a deletion of `C` (as expected).
I will try to implement the renaming detection at this level.

Thanks again!
