### ISSUE TITLE
Applying actions to TreeContext

### ISSUE THREAD

**Issue by FlorianLehmann** [GumTreeDiff/gumtree#97]
Hi, I’m trying to apply a list of Action to a TreeContext and it seems that there are some unexpected behavior. I'm using the JDT generator.

Let me introduce the context :
I have two files ‘left’ and ‘right’ that I compare to generate a list of actions.
This list of actions correspond to the actions needed to go from Left to Right. 
I tried to apply these actions to the left file using the method declared in the class ActionUtil : public static TreeContext apply(TreeContext context, List<Action> actions).

These steps are done with this code:

```java
      File left = new File(“src/main/resources/Left.java”);
      File right = new File(“src/main/resources/Right.java”);

      TreeContext leftTree = new JdtTreeGenerator().generateFromFile(left);
      TreeContext rightTree = new JdtTreeGenerator().generateFromFile(right);
      Matcher m = Matchers.getInstance().getMatcher(leftTree.getRoot(), rightTree.getRoot());
      m.match();

      ActionGenerator g = new ActionGenerator(leftTree.getRoot(), rightTree.getRoot(), m.getMappings());
      List<Action> actions = g.generate();

      System.out.println(leftTree.toString());

      System.out.println(“$$$$$$$$$$$$$$$$$$$$$$“);

      System.out.println(ActionUtil.apply(leftTree, g.getActions()).toString());
```

and these files:

Left.java

```java
public class Main {

   public static void main(Integer[] args) {
       String foo;
   }

}
```

Right.java

```java
public class Main {

   public static void main(Integer[] args) {
       String var;
       String foo;
   }

}
```
and I get this output

```
(() (15 “CompilationUnit” “” ((0 95)) (
   (55 “TypeDeclaration” “” ((0 95)) (
       (83 “Modifier” “public” ((0 6)) ()
       (42 “SimpleName” “Main” ((13 4)) ()
       (31 “MethodDeclaration” “” ((25 67)) (
           (83 “Modifier” “public” ((25 6)) ()
           (83 “Modifier” “static” ((32 6)) ()
           (39 “PrimitiveType” “void” ((39 4)) ()
           (42 “SimpleName” “main” ((44 4)) ()
           (44 “SingleVariableDeclaration” “” ((49 14)) (
               (5 “ArrayType” “Integer[]” ((49 9)) (
                   (43 “SimpleType” “Integer” ((49 7)) (
                       (42 “SimpleName” “Integer” ((49 7)) ())
                   (85 “Dimension” “” ((56 2)) ())
               (42 “SimpleName” “args” ((59 4)) ())
           (8 “Block” “” ((65 27)) (
               (60 “VariableDeclarationStatement” “” ((75 11)) (
                   (43 “SimpleType” “String” ((75 6)) (
                       (42 “SimpleName” “String” ((75 6)) ())
                   (59 “VariableDeclarationFragment” “” ((82 3)) (
                       (42 “SimpleName” “foo” ((82 3)) ())))))))
$$$$$$$$$$$$$$$$$$$$$$
(() (15 “CompilationUnit” “” ((0 95)) (
   (55 “TypeDeclaration” “” ((0 95)) (
       (83 “Modifier” “public” ((0 6)) ()
       (42 “SimpleName” “Main” ((13 4)) ()
       (31 “MethodDeclaration” “” ((25 67)) (
           (83 “Modifier” “public” ((25 6)) ()
           (83 “Modifier” “static” ((32 6)) ()
           (39 “PrimitiveType” “void” ((39 4)) ()
           (42 “SimpleName” “main” ((44 4)) ()
           (44 “SingleVariableDeclaration” “” ((49 14)) (
               (5 “ArrayType” “Integer[]” ((49 9)) (
                   (43 “SimpleType” “Integer” ((49 7)) (
                       (42 “SimpleName” “Integer” ((49 7)) ())
                   (85 “Dimension” “” ((56 2)) ())
               (42 “SimpleName” “args” ((59 4)) ())
           (8 “Block” “” ((65 27)) (
               (60 “VariableDeclarationStatement” “” ((75 11)) (
                   (43 “SimpleType” “String” ((75 6)) (
                       (42 “SimpleName” “String” ((75 6)) ()
                       (42 “SimpleName” “String” ((75 6)) ())
                   (59 “VariableDeclarationFragment” “” ((82 3)) (
                       (42 “SimpleName” “var” ((82 3)) ()
                       (42 “SimpleName” “var” ((82 3)) ())
                   (43 “SimpleType” “String” ((75 6)) (
                       (42 “SimpleName” “String” ((75 6)) ()
                       (42 “SimpleName” “String” ((75 6)) ())
                   (59 “VariableDeclarationFragment” “” ((82 3)) (
                       (42 “SimpleName” “var” ((82 3)) ()
                       (42 “SimpleName” “var” ((82 3)) ()))
               (60 “VariableDeclarationStatement” “” ((75 11)) (
                   (43 “SimpleType” “String” ((75 6)) (
                       (42 “SimpleName” “String” ((75 6)) ())
                   (59 “VariableDeclarationFragment” “” ((82 3)) (
                       (42 “SimpleName” “foo” ((82 3)) ()))))))) 
```
It seems that action are applied two times

Using the same program described earlier but changing the two files :

Left.java

```java
public class Main {

   public void method() {

   }

   public static void main(String[] args) {
       String var;
   }

}
```

Right.java

```java
public class Main {

   public static void main(String[] args) {
       String var;
   }

   public void method() {

   }

}
```

i got this exception Exception 

```
in thread “main” java.lang.IndexOutOfBoundsException: Index: 4, Size: 3
    at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:665)
    at java.util.ArrayList.add(ArrayList.java:477)
    at com.github.gumtreediff.tree.Tree.insertChild(Tree.java:83)
    at com.github.gumtreediff.actions.ActionUtil.apply(ActionUtil.java:43)
    at Main.main(Main.java:33)
```

Thanks!

**Comment by ttben** [comment]
Hi there! :)
I don't know if I misunderstood what `gumtree` is telling you **or** if it gives misleading information.

Here is what I've done:
- I retrieved the latest version of `gumtree`, and build it from sources.
- `./gumtree webdiff path/to/Left.java path/to/Right.java`
- Opened the browser and pressed `l` then `script`. This should display the `edit script` to go from ` left` to `right`.
- It shows the `match` actions along with the `modification` actions (`insert`, `delete`, ...)
- The script seems to be fine..

It displays 

``` 
Match VariableDeclarationStatement(16) to VariableDeclarationStatement(21)
Match SimpleName: main(5) to SimpleName: main(5)
Match SimpleType: String(13) to SimpleType: String(18)
Match Modifier: public(2) to Modifier: public(2)
Match TypeDeclaration(19) to TypeDeclaration(24)
Match SimpleName: String(12) to SimpleName: String(17)
Match SimpleType: Integer(7) to SimpleType: Integer(7)
Match SimpleName: args(10) to SimpleName: args(10)
Match Block(17) to Block(22)
Match SimpleName: foo(14) to SimpleName: foo(19)
Match PrimitiveType: void(4) to PrimitiveType: void(4)
Match ArrayType: Integer[](9) to ArrayType: Integer[](9)
Match MethodDeclaration(18) to MethodDeclaration(23)
Match SimpleName: Main(1) to SimpleName: Main(1)
Match Dimension(8) to Dimension(8)
Match SingleVariableDeclaration(11) to SingleVariableDeclaration(11)
Match SimpleName: Integer(6) to SimpleName: Integer(6)
Match Modifier: public(0) to Modifier: public(0)
Match VariableDeclarationFragment(15) to VariableDeclarationFragment(20)
Match CompilationUnit(20) to CompilationUnit(25)
Match Modifier: static(3) to Modifier: static(3)
Insert VariableDeclarationStatement(16) into Block(22) at 0
Insert SimpleType: String(13) into VariableDeclarationStatement(16) at 0
Insert VariableDeclarationFragment(15) into VariableDeclarationStatement(16) at 1
Insert SimpleName: String(12) into SimpleType: String(13) at 0
Insert SimpleName: var(14) into VariableDeclarationFragment(15) at 0
```
It inserts a declaration of a variable, of type `String`, named `String` (??), with a fragment that is named `var`.

**thus** -> I think the display of `System.out.println(ActionUtil.apply(leftTree, g.getActions()).toString());` **may be** misleading

Note:
> Executing `System.out.println(ActionsIoUtils.toText(leftTree, g.getActions(), m.getMappings()));` . can help you to read the actions.

Either the mapping is broken (which is weird), or we both forgot to `init` something.

**Comment by ttben** [comment]
I think you should focus on the edit script only (ie `ActionsIoUtils.toText(leftTree, g.getActions(), m.getMappings())` and not on their application)

**Comment by yueguangxuanyuan** [comment]
this bug has not been repaired.
i retrieve the source code , the apply method  seems to be wrong , the restore process just use the node in dst tree,

**Comment by jrfaller** [comment]
Yes the bug has not been fixed yet because it requires to rethink how we compute the actions. But it's definitively on the TODO list.

**Comment by jrfaller** [comment]
OK closing this because this method has been removed in the develop branch, but if some of you are still interested in an API to execute actions on tree, don't hesitate to post a feature requestion! Cheers.
